name: SlackNot

on:
  pull_request:
    branches: [ main, develop]

jobs: 
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel"\:\"C069ZMB8CSW\",\"text\":\"Test-text\"}'