name: Deploy

on:
  push:
    branches:
      - main

env: 
  VITE_MAILING_ENDPOINT: ${{ secrets.VITE_MAILING_ENDPOINT }}
  VITE_MAILING_RECIPIENT: ${{ secrets.VITE_MAILING_RECIPIENT }}
  VITE_WHATSAPP_PHONE: ${{ secrets.VITE_WHATSAPP_PHONE}}

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      actions: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set Node Enviro
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          bun install --include=optional

      
      - name: Build Website
        run: bun run build


      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Copy to S3
        run: aws s3 sync ./dist/. s3://kamino-web
      